from app.models.usuario import Usuario
from app.models.coordenador import Coordenador
from app.models.professor import Professor
from app.models.curso import Curso
from app.models.semestre import Semestre
from app.models.turma import Turma
from app.models.disciplina import Disciplina
from app.models.horario import Horario
from app.models.disponibilidade import Restricao
from app.models.disponibilidade_turma import DisponibilidadeTurma
from app.models.preferencias_professor import PreferenciaProfessor
from app.models.oferta_disciplina import OfertaDisciplina
from app.models.alocacao import Alocacao